# This is an example sqlboiler.toml file for PostgreSQL

# The name of the generated package
[generated_package]
name = "models"

# The database connection information
[psql]
dbname = "go_lang"
host = "localhost"
user = "postgres"
pass = "root"
port = 5432
sslmode = "disable"
